name: Canvas Grade Notifier

on:
  schedule:
    # Runs every hour at the top of the hour (UTC)
    - cron: "0 * * * *"
  workflow_dispatch:
    # Allows you to run it manually from GitHub's website at any time

jobs:
  check-canvas:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download your repository files (including seen_grades.json / seen_assignments.json)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3: Install the requests library
      - name: Install dependencies
        run: pip install requests

      # Step 4: Run the notifier script
      - name: Run Canvas notifier
        env:
          CANVAS_URL = "https://crms.instructure.com"
          CANVAS_API_TOKEN = "8069~FenRExLAFVcuMTAv6GFTAKUhJ8AJMFNam8MFBUXN9CFkyanPu4ZxJ4m8BwReLHVY"
          NTFY_TOPIC = "jsmith-canvas-8472"
        run: python canvas_grade_notifier.py

      # Step 5: Save the updated seen_grades.json and seen_assignments.json
      # back to the repository so next run knows what was already notified
      - name: Save updated grade/assignment state
        run: |
          git config user.name  "GitHub Actions"
          git config user.email "actions@github.com"
          git add seen_grades.json seen_assignments.json
          git diff --cached --quiet || git commit -m "Update seen grades/assignments [skip ci]"
          git push
